### ISSUE TITLE
Datastream names should be human readable by default.

### ISSUE THREAD

**Issue by kjlippold** [hydroserver2/hydroserver#112]
### Describe the feature you'd like and what it will do

We're currently copying the datastream UUID over to the datastream name field. The SensorThings specification suggests using a descriptive name in this field rather than a UUID.

The datastream name and description should probably continue to be autogenerated by default at least. We could use the pattern we're using for descriptions on the name field instead and come up with a longer more descriptive string for the description.

Name pattern: "{sampled_medium} {observed_property_name} at {thing_name} - {processing_level_name}"
Description pattern: "An {status} datastream of observations containing {sampled_medium} {observed_property_name} measurements at {thing_name} using a {sensor_name} with the following processing level: {processing_level_name}."

When a user creates a datastream, the form should present these autogenerated values for them to use, but we should also give them the option to edit them rather than force these patterns on all datastreams.

### Why is this feature important?

This will help datastream responses be more human readable and bring our SensorThings implementation more in line with the specification.

**Comment by horsburgh** [comment]
We need to make sure we don't include any optional attributes in the concatenation patterns or they may break down. I suggest:

Name Pattern: 

"ObservedProperty.name + " at " + Thing.samplingFeatureCode + " with processing level "  + ProcessingLevel.processingLevelCode"

Description Pattern:

"A datastream of ObservedProperty.name + " at " + Thing.name + " with processing level "  + ProcessingLevel.processingLevelCode + " and sampled medium " + Datastream.sampledMedium + " created using a method with name " + Sensor.name

**Comment by daniel-slaugh** [comment]
@horsburgh Should we include the unit of measurement in the name or description too?

**Comment by horsburgh** [comment]
We could try it in the Description:

"A datastream of ObservedProperty.name + " at " + Thing.name + " with processing level " + ProcessingLevel.processingLevelCode + " and sampled medium " + Datastream.sampledMedium + " created using a method with name " + Sensor.name + " having units of " Unit.Name
