### ISSUE TITLE
GitHub Flow

### ISSUE THREAD

**Issue by daniel-slaugh** [hydroserver2/hydroserver#121]
Currently, we have dev and main branches following Gitflow Workflow, but the only difference between dev and main is that we're automatically deploying dev to AWS on push. We could still do that if we just had a main branch which would save us some CI/CD time.  Also, we could improve our GitHub actions scripts to follow GitHub Flow better and get rid of some unused GitHub secrets.

**Comment by horsburgh** [comment]
I think we need to discuss this. I would like to understand the implications before we get rid of dev.
