### ISSUE TITLE
Can't Update Datastream Name or Description

### ISSUE THREAD

**Issue by daniel-slaugh** [hydroserver2/hydroserver#152]
### Steps to Reproduce

Go to the datastream form page, edit the datastream's name or description and submit the form. 

### Expected Behavior

Should update

### Actual Behavior

Console.logging shows the frontend sends the right patch request but the backend doesn't update the fields.

**Comment by kjlippold** [comment]
https://github.com/hydroserver2/hydroserver-webapp-back/pull/186
