### ISSUE TITLE
Make Schemas Match Lucidchart Diagram 

### ISSUE THREAD

**Issue by daniel-slaugh** [hydroserver2/hydroserver#169]
I went through and compared HydroServer's models with our LucidCharts diagram to make sure everything matches and found the following discrepancies. For any changes, we'll need to make sure the backend, frontend, and Lucidchart are all the same: 

- [x] DataSource.URL -  This is the same everywhere, but the other tables use 'link' as the field name when referring to a web URL. Do we want to update this? 
- [x] ThingAssociation.followsThing - This should be deleted everywhere since we're not using it anymore.
- [x] Observation.validBeginTime & validEndTime - present in Lucid but not the db. But there's a "suggest not using" note in Lucid. Do we care that the fields are missing in the db?

**Comment by kjlippold** [comment]
Created an issue cleaning up follower functionality: https://github.com/hydroserver2/hydroserver/issues/170
