### ISSUE TITLE
Save state of "Items per page" selection on My Sites page and site details page

### ISSUE THREAD

**Issue by horsburgh** [hydroserver2/hydroserver#195]
### Describe the feature you'd like and what it will do

When a user selects the number of items they want to display on a page (e.g., the number of sites or the number of datastreams) that selection should persist at least for the duration of the user's session on the site. It's annoying to set it and then when the page refreshes or you navigate away and then come back the setting has been cleared out.

### Why is this feature important?

Trying not to annoy users by making them set a preference multiple times.

### Is your feature request related to a problem? Please describe.

NA

### Any additional comments?

NA

**Comment by horsburgh** [comment]
This will also apply to the data management pages.

**Comment by daniel-slaugh** [comment]
@horsburgh What if we do what the qc app does and swap out the Vuetify v-data-table with the v-data-table-virtual, so no pagination, just scrolling. Then maybe put a search bar at the top too? I could also do this for the metadata tables.

QC app table: 
![image](https://github.com/user-attachments/assets/e6ab9453-adc1-4c9d-b666-85ed6a4e588d)

**Comment by horsburgh** [comment]
I think this is fine as I assume that it covers this issue. I'm hoping this won't be a massive change and that it will be a pretty straightforward swap.
