### ISSUE TITLE
Axis labels are overlapping with tic mark labels on plots

### ISSUE THREAD

**Issue by horsburgh** [hydroserver2/hydroserver#198]
### Steps to Reproduce

Viewing the data that the Holt Farms/Husqvarna group just added to the DWRi HydroServer instance, when the y-axis tic mark labels are large numbers they overlap with the text label of the axis.

### Expected Behavior

The axis label should appear to the left of the tic mark labels, and they should not overlap. May have to figure out some dynamic scaling to get this to work correctly.

### Actual Behavior

<img width="582" alt="image" src="https://github.com/user-attachments/assets/67034f4f-0d1c-4623-9e68-3c49a9d7dba8">

**Comment by daniel-slaugh** [comment]
Dynamic spacing could be done by getting the min and max value of a dataset and setting the margin based on the number of digits. Though if someone's data is recorded with very large numbers in the billions or trillions for some reason, the page may run out of horizontal space. 

An alternative is to use scientific notation on any number bigger than a million: 
![image](https://github.com/user-attachments/assets/9baa3f22-4417-485b-999b-be02dc1171dd)

**Comment by horsburgh** [comment]
Yes, I think scientific notation for any value greater than 1E6 is a good idea.
