### ISSUE TITLE
The isDataVisible flag should only hide sparkline.

### ISSUE THREAD

**Issue by kjlippold** [hydroserver2/hydroserver#203]
### Steps to Reproduce

1. Set isDataVisible for a datastream to False.
2. Visit the Site Details page while not logged in.

### Expected Behavior

The datastream should appear on the datastream table, but the sparkline should be hidden.

### Actual Behavior

The entire datastream is hidden from the table. The whole datastream should only be hidden if the "isVisible" flag is set to False.

**Comment by daniel-slaugh** [comment]
@kjlippold It looks like the problem is the backend isn't returning the datastreams if the client tries to fetch datastream as a guest and datastream.isDataVisible is false for the `${THINGS_BASE}/${thingId}/datastreams` endpoint. The API should return the datastream, just not the observations.
