### ISSUE TITLE
Add additional values to SiteType dropdown.

### ISSUE THREAD

**Issue by kjlippold** [hydroserver2/hydroserver#205]
### Describe the feature you'd like and what it will do

The SiteType dropdown of the data management app needs the following additional values:
* Irrigation Pivot
* Groundwater Well
* Calculated

### Why is this feature important?

These are commonly used values for the SiteType field.

**Comment by daniel-slaugh** [comment]
This issue started the discussion that ended in the decision to implement the functionality in hydroserver2/hydroserver#208
