### ISSUE TITLE
Guests Can't Access Site Details Page

### ISSUE THREAD

**Issue by daniel-slaugh** [hydroserver2/hydroserver#23]
### Steps to Reproduce

Navigate to the SiteDetails page of any Site as an guest

### Expected Behavior

User should be able to see all the data, visible datastreams, and metadata for the site, as well as the observations plot for any of the datastreams

### Actual Behavior

User gets redirected to the login page with either a 400 Bad request on token refresh or a 403 forbidden on the metadata request

**Comment by kjlippold** [comment]
Thing metadata now allows for anonymous user and non-owner GET access. Verified that users can now access the site details page without being logged in on the dev site.

https://github.com/hydroserver2/hydroserver-webapp-back/pull/144
