### ISSUE TITLE
Site markers on Browse Monitoring Sites no longer display organization information

### ISSUE THREAD

**Issue by horsburgh** [hydroserver2/hydroserver#32]
### Steps to Reproduce

The Google Maps pop up for a site used to display the organization associated with the site owner. This was useful information. Now it no longer displays. Also, the styling of the "View Data for this Site" link/button seems off.

<img width="474" alt="image" src="https://github.com/hydroserver2/hydroserver/assets/3485902/edc512d0-88bc-4d42-8f93-da1da155d8f4">

### Expected Behavior

Display organization name associated with the site owner in the site information pop-up.

### Actual Behavior

No organization is shown in the site information pop-up.

**Comment by daniel-slaugh** [comment]
I submitted the pull request to fix the missing organization name. I can't seem to reproduce the bad styling of the 'view data for this site' button.
