### ISSUE TITLE
Improve cache invalidation

### ISSUE THREAD

**Issue by kjlippold** [hydroserver2/hydroserver#33]
Our current frontend caching method doesn't take into account changes made to the backend through non-browser API calls or other browser sessions. This is especially noticeable when pushing observations to the site via the streaming data loader and not being able to see the new data on the single site page until the user logs out and back in.

Currently, the frontend will load any data from the API once and cache it in local storage, and to invalidate the cache requires some frontend trigger condition. I think we have a couple options for improving cache invalidation.

1. Using our existing setup, let the user manually invalidate the existing cache for certain data via a refresh button on the data table or page that needs to be updated, or maybe upon refreshing the page via the browser.
2. Add an age check to cached data, so that after some amount of time the browser would refresh the data from the backend. This could be configured for each store.
3. Anytime a store is loaded, use the cached data to initially populate the page, but also refresh the data from the backend. This would result in more API calls, but it would keep the data the most up-to-date while still letting us load pages quickly. Users might sometimes see old data for a second before the updated data pops in. Not sure if this is desirable or not.
4. Remove caching entirely for certain stores that are likely to change outside the browser session, such as datastreams. The main drawback is that these pages or portions of the pages would always take a little longer to load, but the data would always be fresh.

We can also explore some backend caching strategies using Django and CloudFront if we're concerned about the frequency of database queries, but that would likely be more complicated to implement correctly due to the nature of our data model.

**Comment by kjlippold** [comment]
We probably need to look into adding either a database trigger or Django signal that maintains a last modified field for our DB tables. Based on that field, we can add a filter to each endpoint that allows users to retrieve data that's been modified since a given timestamp. We could also use this as a starting point for maintaining an audit trail for DB changes through the API.

**Comment by kjlippold** [comment]
I'm considering using https://github.com/jazzband/django-simple-history to track changes on the Django end. With that, we should also be able to update the data management API to include a Last-Modified header in responses, and accept an If-Modified-Since header on requests.

**Comment by daniel-slaugh** [comment]
Turning caching off completely and getting only the data we need for each page is working fast enough. Closing this issue for now
