### ISSUE TITLE
Frontend sign up pages not redirecting properly

### ISSUE THREAD

**Issue by kjlippold** [hydroserver2/hydroserver#41]
### Steps to Reproduce

- Sign up for a new account and enter user info.
- Click "Create User"
- Verify email address

### Expected Behavior

After clicking "Create User", the user should be automatically redirected to the verify email page. After verifying their email, they should be redirected to the "My Sites" page.

### Actual Behavior

Clicking "Create User" does not redirect the user anywhere. After verifying their email, the user is told their email couldn't be verified even though it was.

**Comment by daniel-slaugh** [comment]
I fixed some related routing issues this week that may have fixed this problem. I tested localhost and dev with the new code and both work as expected. I'm going to check this works on beta once we release
