### ISSUE TITLE
Terms of Use and Privacy Statements

### ISSUE THREAD

**Issue by daniel-slaugh** [hydroserver2/hydroserver#6]
- [x] Write Terms of Use 
 - [x] Write Privacy statements
 - [x] Home page links to both documents

**Comment by horsburgh** [comment]
@daniel-slaugh - I have drafted terms of use and privacy statements for HydroServer:

Terms of Use: https://docs.google.com/document/d/1bCv7y3mZOIWCS6AcaCidpZ3Xsr71sItIZ-AbfX7M3GY/edit 

Privacy Policy: https://docs.google.com/document/d/1nC_R5_wbghyG29qlF1CbT0gN2crhAYYmoajql0dI8_0/edit

It would be nice if these were implemented in such a way that they could be easily replaced. For example, could they be markdown documents that can just be swapped out by anyone who wants to run their own instance of HydroServer?

**Comment by daniel-slaugh** [comment]
@horsburgh - Awesome. I can convert these to markdown and put them in our main HydroServer repo, then point the frontend to those markdown files. As far as allowing user to swap out their own, maybe that could be added as a user preference? (hydroserver2/hydroserver#101)

**Comment by horsburgh** [comment]
@daniel-slaugh - it's not so much a user preference as it would be a configuration issue. Could this be a deployment configuration setting?
