### ISSUE TITLE
Scheduled & On-Demand HydroShare Archival

### ISSUE THREAD

**Issue by daniel-slaugh** [hydroserver2/hydroserver#7]
- [ ] Add UI for user to add archival configuration settings and metadata
- [ ] Connect user's account to HydroShare
- [ ]  Archive CSV to HydroShare
- [ ]  "Edit this resource in HydroShare" button
- [ ] On the “Connect Account to HydroShare” card, change the text to “Connect My HydroShare Account”. Then add the following text below that: “HydroServer allows you to archive your time series data to the HydroShare repository. Before doing so, you must link your HydroShare account to your HydroServer user account. Click the “Connect” button and follow the directions to link your accounts.”

**Comment by horsburgh** [comment]
Yes - I think it makes sense to have a 1:1 mapping between a Site/Thing and a HydroShare resource. Then, I think the user should select which datastreams they want to archive into that resource. I do think we might need to allow users to create folders within the resource and map datastreams to a folder. For example, one folder for raw data and one folder for quality controlled data. There may be other organizations that people want to use.

I think the CSV download format that @daniel-slaugh has implemented should suffice for the datastream archival file format.

We probably need to create a limited set of archival frequencies - e.g., daily, weekly, monthly. We'll also have to decide whether that frequency applies at the site/thing level or at the datastream level.

**Comment by horsburgh** [comment]
I think there should be one archival configuration per site. So, once a site is set up to archive to HydroShare, it should be set up under whoever initially set it up, unless that is transferred to another user. It should only be set to archive to one HydroShare resource - not multiple. 

I think any site owner should be able to configure the site to archive to HydroShare.

**Comment by kjlippold** [comment]
On-demand HydroShare archival has been implemented.

https://github.com/hydroserver2/hydroserver-webapp-back/pull/163
https://github.com/hydroserver2/hydroserver-webapp-front/pull/48

Scheduled HydroShare archival will be added once we set up a process for handling scheduled tasks.
