### ISSUE TITLE
Cannot Access Django Admin Panel on Beta Instance 

### ISSUE THREAD

**Issue by daniel-slaugh** [hydroserver2/hydroserver#77]
### Steps to Reproduce

Navigate to https://beta.hydroserver2.org/admin/

### Expected Behavior

This should open Django's admin panel login page. On entering admin credentials, user should be navigated to Django's admin panel 

### Actual Behavior

User is directed to an unstyled login page. On entering credentials, the following CloudFront error is thrown:

 403 ERROR
The request could not be satisfied.
This distribution is not configured to allow the HTTP request method that was used for this request. The distribution supports only cachable requests. We can't connect to the server for this app or website at this time. There might be too much traffic or a configuration error. Try again later, or contact the app or website owner.
If you provide content to customers through CloudFront, you can find steps to troubleshoot and help prevent this error by reviewing the CloudFront documentation.
Generated by cloudfront (CloudFront)
Request ID: VRiJuU7k3H_fXHMUa7T8gLSZkdWe8IbjlPSLbxaZXM-hB7LjmZ4uDw==

**Comment by kjlippold** [comment]
Static files had been copied to the wrong S3 folder and couldn't be found. The issue has been resolved for the beta deployment.
