### ISSUE TITLE
User Type

### ISSUE THREAD

**Issue by daniel-slaugh** [hydroserver2/hydroserver#80]
We need a controlled vocabulary (could be the same as HydroShare) for user type

**Comment by horsburgh** [comment]
Here is the list of HydroShare's user types:

<img width="322" alt="image" src="https://user-images.githubusercontent.com/3485902/234937767-3e774a1e-52d7-4f40-a30d-dd1a8cc69d4a.png">

**Comment by daniel-slaugh** [comment]
Added user type as string to database and website signup and edit pages. Copied HydroShare's user types as list to frontend
