### ISSUE TITLE
Delete User Endpoint

### ISSUE THREAD

**Issue by daniel-slaugh** [hydroserver2/hydroserver#83]
### Steps to Reproduce

Try to delete a user

### Expected Behavior

This should delete the user and all their data

### Actual Behavior

The frontend calls the correct endpoint: DELETE http://127.0.0.1:8000/api/account/user, but the endpoint no longer exists on the backend

**Comment by kjlippold** [comment]
@horsburgh @daniel-slaugh Do we want the delete user endpoint to immediately delete the user and their data? It might be safer to have the endpoint set the is_active flag to false for the user, hide all their data, and prevent them from logging in, and then actually delete inactive users some period of time after their last login. From the user's perspective the account would be deleted immediately, but there would be a backdoor for a period of time where an admin user could still recover their account if necessary.

**Comment by horsburgh** [comment]
@kjlippold - this is probably a good idea. Maybe have a 30 day delay on actual deletion?

**Comment by kjlippold** [comment]
@horsburgh Sounds good, I'll go ahead and do that.

**Comment by daniel-slaugh** [comment]
@horsburgh @daniel-slaugh The only problem I can imagine is having to make the backend more complex. If the user deletes their account, I think we want to prevent their sites from getting retrieved when the api calls all sites or a user navigates to the /Browse page. Then we'd need to think about what happens if a site to be deleted has secondary owners. 

I think it's a good feature so long as it doesn't add too much complexity.

**Comment by kjlippold** [comment]
@daniel-slaugh Generally, we should be able to just check the is_active field when we apply auth rules to our queries and filter the results accordingly.

**Comment by kjlippold** [comment]
https://github.com/hydroserver2/hydroserver-webapp-back/pull/166
