### ISSUE TITLE
Organization filter is not working/displaying correctly

### ISSUE THREAD

**Issue by horsburgh** [hydroserver2/hydroserver#85]
### Steps to Reproduce

1. Go to the Browse Monitoring Sites page
2. Enter "Utah" in the "Filter by Organizations" text box
3. Click the "Filter" button
4. Observe text below the filter box

### Expected Behavior

I'm not sure how this is supposed to work. What if there are multiple organizations with "Utah" in the name? Can I select one? Can I select many? Or, do I have to control all selected terms through my search term? Seems like this worked without me getting confused before.

### Actual Behavior

This is what is displayed. The spacing seems odd, the text is outside the filter box, so the user may be confused about what it is and why it is there:

<img width="447" alt="image" src="https://github.com/hydroserver2/hydroserver/assets/3485902/e608828e-b1c2-4e04-9403-0ddfa529dcc3">

**Comment by daniel-slaugh** [comment]
I have some formatting changes for this going into v0.4.0. Here's the current UI: 
<img width="135" alt="image" src="https://github.com/hydroserver2/hydroserver/assets/83979385/c6970779-0280-4115-a6de-479df8a9508d">
What this does is display a unique list of the organizations that contain the search text. No selection abilities, It's just a convenience to let the user know how many organizations their search term matches.

**Comment by horsburgh** [comment]
That's better. Having the appear inside the box will make it less confusing.
