### ISSUE TITLE
Time Series Plot with data gaps

### ISSUE THREAD

**Issue by daniel-slaugh** [hydroserver2/hydroserver#98]
### Describe the feature you'd like and what it will do

If a dataset has a gap between data points larger than the intended time spacing value, we should show that gap (break the line) on the Time Series Plot. 

### Why is this feature important?

If there's no data for a given time period, we want the user to be aware of that

### Any additional comments?

@horsburgh I'm thinking we'll need to restrict the intended_time_spacing_units_id to just seconds, minutes, hours, and days otherwise the time unit conversions will get out of hand. Is that something we can do?

**Comment by horsburgh** [comment]
I think limitation of the units for intended time spacing to seconds, minutes, hours, and days is reasonable.
